title: SAHITHI YARLAPATI
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  FI'm Sahithi Yarlapati, a second-year B.Tech student in Computer Science Engineering with a focus on Cybersecurity. I’m deeply passionate about coding, problem-solving, and pushing the boundaries of my technical abilities. With a keen eye for computational logic and a growing expertise in cybersecurity, I’m driven to understand the complexities of data protection.
  <br><br>
  Beyond academics, I'm an avid reader who values knowledge and perspective from all fields. I’m actively involved in engineering societies where I contribute to tech-driven projects aimed at community impact. I thrive in collaborative settings and am always seeking opportunities to connect, learn, and grow within the tech industry.
  <br><br>
  My goal? To combine my skills in cybersecurity and software development to create innovative, secure solutions that make a real difference. I’m excited to step into roles where I can make meaningful contributions while continuing to learn and evolve as an engineer.
 
  <br><br>
  <a href="https://www.linkedin.com/in/sahithi-y-07a1ba267/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
